// Browser download orchestration (docs/APPLICATION_LAYOUT.md "Download
// Flow"; the approved Download-behavior decision, "Variante A"). Triggers
// the ordinary Blob-/anchor-`download`-attribute browser download exactly
// once per call, with no attempt to detect whether it actually started or
// was blocked — no reliable, non-heuristic browser signal for that exists
// (see docs/IMPLEMENTATION_PLAN_V1.md Phase 9's own Risks entry for the
// evidence). `Download again` (src/components/OutputInspector.tsx) calls
// this same function again with the identical already-generated bytes —
// never a new generation cycle.

export interface GeneratedArtifact {
	readonly filename: string;
	readonly mimeType: string;
	readonly bytes: Uint8Array;
}

// Object URLs are cheap and this is called at most a handful of times per
// Output Inspector session — a fresh one per call, revoked shortly after,
// is simpler and just as correct as trying to keep one alive across
// repeated `Download again` presses.
const REVOKE_DELAY_MS = 30_000;

export function triggerDownload(artifact: GeneratedArtifact): void {
	const blob = new Blob([artifact.bytes as unknown as BlobPart], {
		type: artifact.mimeType,
	});
	const url = URL.createObjectURL(blob);
	const anchor = document.createElement("a");
	anchor.href = url;
	anchor.download = artifact.filename;
	anchor.rel = "noopener";
	document.body.appendChild(anchor);
	anchor.click();
	anchor.remove();
	// Deferred, not immediate: revoking synchronously right after `.click()`
	// has been observed to race the browser's own read of the blob URL in
	// some engines. `Download again` is unaffected either way — it always
	// creates its own fresh object URL from the same underlying bytes.
	setTimeout(() => URL.revokeObjectURL(url), REVOKE_DELAY_MS);
}
