import {
	boolean,
	char,
	mysqlTable,
	text,
	timestamp,
	varchar,
} from "drizzle-orm/mysql-core";

export const comparisons = mysqlTable("comparisons", {
	// UUID, generated by the application (not the database) — see docs/ARCHITECTURE.md "Identifiers"
	id: char("id", { length: 36 }).primaryKey(),

	// stored session.comparisonId; enforces at most one active Hosted Publication per Comparison
	comparisonId: char("comparison_id", { length: 36 }).notNull().unique(),

	publicId: varchar("public_id", { length: 12 }).notNull().unique(),

	// hash only; the plaintext management token is never stored
	managementTokenHash: varchar("management_token_hash", { length: 64 })
		.notNull()
		.unique(),

	title: varchar("title", { length: 255 }),
	description: text("description"),
	referenceLabel: varchar("reference_label", { length: 255 }).notNull(),
	captureLabel: varchar("capture_label", { length: 255 }).notNull(),
	showDate: boolean("show_date").notNull().default(true),

	locationDisplayName: varchar("location_display_name", { length: 255 }),
	locationCity: varchar("location_city", { length: 255 }),
	locationCountry: varchar("location_country", { length: 255 }),

	brandingType: varchar("branding_type", { length: 50 }),
	brandingBuiltinId: varchar("branding_builtin_id", { length: 100 }),

	background: varchar("background", { length: 10 }).notNull(),
	cornerStyle: varchar("corner_style", { length: 10 }).notNull(),

	// identifies the currently active, immutable versioned asset set (see
	// docs/ARCHITECTURE.md "Asset Storage") — nullable, no default; not yet
	// written by any code (first writer is the Publish API)
	activeAssetVersion: varchar("active_asset_version", { length: 36 }),

	// operational publication state, required for atomic activation (see
	// docs/ARCHITECTURE.md "Publication Update Atomicity"); Phase 3 only
	// establishes the column, single value 'active' for now
	status: varchar("status", { length: 20 }).notNull().default("active"),

	createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
	updatedAt: timestamp("updated_at", { mode: "date" })
		.notNull()
		.defaultNow()
		.onUpdateNow(),
});

export type Comparison = typeof comparisons.$inferSelect;
export type NewComparison = typeof comparisons.$inferInsert;
