<?php
/**
 * The minimal `SameView → Add comparison` admin workflow
 * (docs/EMBED_IN_WEBSITE.md "Comparison Lifecycle"; docs/WORDPRESS_INTEGRATION.md
 * "Permissions and Security"). One admin page with a single file-upload
 * form, gated by the `manage_sameview_comparisons` capability
 * (includes/capabilities.php) — no library/listing UI, no Delete
 * (docs/IMPLEMENTATION_PLAN_V1.md Phase 15 "Not included": "Comparison
 * Management library/listing UI").
 *
 * The upload handler validates the uploaded ZIP's own structural safety
 * completely (size, entry count, path traversal, nested archives — the same
 * principles src/lib/import-archive.ts already applies on the SameView Web
 * side, reimplemented here in PHP since the two are separate languages/
 * deliverables) before ever extracting anything, then hands the extracted
 * `seed/` directory to the one shared includes/import.php
 * `sameview_import_seed()` — never a second, duplicated Add/Update/no-op
 * implementation.
 *
 * This file only defines functions; it never calls them at load time except
 * the two hook registrations at the very end, which only ever register
 * callbacks — they do not themselves render anything or touch stored state.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Disallow direct access.
}

define( 'SAMEVIEW_ADD_COMPARISON_ACTION', 'sameview_add_comparison' );
define( 'SAMEVIEW_ADD_COMPARISON_NONCE', 'sameview_add_comparison_nonce' );
define( 'SAMEVIEW_MAX_PACKAGE_BYTES', 25 * 1024 * 1024 );
define( 'SAMEVIEW_MAX_PACKAGE_FILES', 50 );
define( 'SAMEVIEW_MAX_PACKAGE_UNCOMPRESSED_BYTES', 100 * 1024 * 1024 );

function sameview_register_admin_menu() {
	add_management_page(
		'SameView Comparisons',
		'SameView',
		SAMEVIEW_CAPABILITY,
		'sameview-add-comparison',
		'sameview_render_add_comparison_page'
	);
}

function sameview_render_add_comparison_page() {
	if ( ! current_user_can( SAMEVIEW_CAPABILITY ) ) {
		wp_die( esc_html__( 'You do not have permission to manage SameView Comparisons.', 'sameview-comparisons' ) );
	}

	$status  = isset( $_GET['sameview_status'] ) ? sanitize_key( wp_unslash( $_GET['sameview_status'] ) ) : '';
	$message = isset( $_GET['sameview_message'] ) ? sanitize_text_field( wp_unslash( $_GET['sameview_message'] ) ) : '';

	echo '<div class="wrap"><h1>SameView</h1>';

	if ( $status && $message ) {
		$notice_class = in_array( $status, array( 'added', 'updated', 'no-op' ), true ) ? 'notice-success' : 'notice-error';
		echo '<div class="notice ' . esc_attr( $notice_class ) . '"><p>' . esc_html( $message ) . '</p></div>';
	}

	echo '<h2>' . esc_html__( 'Add comparison', 'sameview-comparisons' ) . '</h2>';
	echo '<p>' . esc_html__( 'Upload a Comparison package generated by SameView Web.', 'sameview-comparisons' ) . '</p>';
	echo '<form method="post" enctype="multipart/form-data" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">';
	wp_nonce_field( SAMEVIEW_ADD_COMPARISON_ACTION, SAMEVIEW_ADD_COMPARISON_NONCE );
	echo '<input type="hidden" name="action" value="' . esc_attr( SAMEVIEW_ADD_COMPARISON_ACTION ) . '">';
	echo '<p><input type="file" name="sameview_package" accept=".zip" required></p>';
	submit_button( __( 'Add comparison', 'sameview-comparisons' ) );
	echo '</form></div>';
}

function sameview_redirect_with_result( $status, $message ) {
	$url = add_query_arg(
		array(
			'page'             => 'sameview-add-comparison',
			'sameview_status'  => $status,
			'sameview_message' => rawurlencode( $message ),
		),
		admin_url( 'tools.php' )
	);
	wp_safe_redirect( $url );
	exit;
}

/**
 * Validates a ZIP's own entry list before anything is ever extracted —
 * path traversal, nested archives, entry count and (uncompressed) size
 * limits, mirroring src/lib/import-archive.ts's own checks on the SameView
 * Web side. Returns true when safe, or a WP_Error describing the first
 * problem found.
 */
function sameview_validate_zip_structure( $zip ) {
	if ( $zip->numFiles > SAMEVIEW_MAX_PACKAGE_FILES ) {
		return new WP_Error( 'sameview_too_many_files', 'This is not a valid SameView Comparison package.' );
	}

	$uncompressed_total = 0;
	for ( $i = 0; $i < $zip->numFiles; $i++ ) {
		$stat = $zip->statIndex( $i );
		if ( false === $stat ) {
			return new WP_Error( 'sameview_invalid_zip', 'This is not a valid SameView Comparison package.' );
		}
		$name = $stat['name'];

		if ( '/' === substr( $name, 0, 1 ) || false !== strpos( $name, '..' ) ) {
			return new WP_Error( 'sameview_unsafe_entry_path', 'This is not a valid SameView Comparison package.' );
		}
		if ( preg_match( '/\.zip$/i', $name ) ) {
			return new WP_Error( 'sameview_nested_archive', 'This is not a valid SameView Comparison package.' );
		}

		$uncompressed_total += $stat['size'];
		if ( $uncompressed_total > SAMEVIEW_MAX_PACKAGE_UNCOMPRESSED_BYTES ) {
			return new WP_Error( 'sameview_package_too_large', 'This is not a valid SameView Comparison package.' );
		}
	}

	return true;
}

function sameview_handle_add_comparison() {
	if (
		! isset( $_POST[ SAMEVIEW_ADD_COMPARISON_NONCE ] )
		|| ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST[ SAMEVIEW_ADD_COMPARISON_NONCE ] ) ), SAMEVIEW_ADD_COMPARISON_ACTION )
	) {
		wp_die( esc_html__( 'Security check failed.', 'sameview-comparisons' ) );
	}
	if ( ! current_user_can( SAMEVIEW_CAPABILITY ) ) {
		wp_die( esc_html__( 'You do not have permission to manage SameView Comparisons.', 'sameview-comparisons' ) );
	}

	if (
		empty( $_FILES['sameview_package'] )
		|| ! isset( $_FILES['sameview_package']['error'] )
		|| UPLOAD_ERR_OK !== $_FILES['sameview_package']['error']
	) {
		sameview_redirect_with_result( 'rejected', __( 'No file was uploaded, or the upload failed.', 'sameview-comparisons' ) );
	}

	// phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- path to an
	// already-uploaded temp file, not user-displayed or stored.
	$tmp_path = $_FILES['sameview_package']['tmp_name'];
	if ( ! is_uploaded_file( $tmp_path ) ) {
		sameview_redirect_with_result( 'rejected', __( 'This is not a valid SameView Comparison package.', 'sameview-comparisons' ) );
	}
	if ( filesize( $tmp_path ) > SAMEVIEW_MAX_PACKAGE_BYTES ) {
		sameview_redirect_with_result( 'rejected', __( 'This is not a valid SameView Comparison package.', 'sameview-comparisons' ) );
	}

	if ( ! class_exists( 'ZipArchive' ) ) {
		sameview_redirect_with_result( 'rejected', __( 'This server cannot process ZIP files.', 'sameview-comparisons' ) );
	}

	$zip    = new ZipArchive();
	$opened = $zip->open( $tmp_path );
	if ( true !== $opened ) {
		sameview_redirect_with_result( 'rejected', __( 'This is not a valid SameView Comparison package.', 'sameview-comparisons' ) );
	}

	$structure_check = sameview_validate_zip_structure( $zip );
	if ( is_wp_error( $structure_check ) ) {
		$zip->close();
		sameview_redirect_with_result( 'rejected', $structure_check->get_error_message() );
	}

	$extract_dir = trailingslashit( get_temp_dir() ) . 'sameview-import-' . wp_generate_password( 12, false );
	wp_mkdir_p( $extract_dir );
	$extracted = $zip->extractTo( $extract_dir );
	$zip->close();

	if ( ! $extracted ) {
		sameview_delete_directory_recursive( $extract_dir );
		sameview_redirect_with_result( 'rejected', __( 'This is not a valid SameView Comparison package.', 'sameview-comparisons' ) );
	}

	// Never touches/replaces the installed plugin's own code
	// (docs/WORDPRESS_INTEGRATION.md "Persistent Integration Versioning") —
	// only this fixed, known-shape subdirectory is ever read.
	$seed_dir = trailingslashit( $extract_dir ) . 'sameview-comparisons/seed';
	if ( ! is_dir( $seed_dir ) ) {
		sameview_delete_directory_recursive( $extract_dir );
		sameview_redirect_with_result( 'rejected', __( 'This is not a valid SameView Comparison package.', 'sameview-comparisons' ) );
	}

	$result = sameview_import_seed( $seed_dir );
	sameview_delete_directory_recursive( $extract_dir );

	sameview_redirect_with_result( $result['status'], $result['message'] );
}

add_action( 'admin_menu', 'sameview_register_admin_menu' );
add_action( 'admin_post_' . SAMEVIEW_ADD_COMPARISON_ACTION, 'sameview_handle_add_comparison' );
