import {
	char,
	mysqlTable,
	text,
	timestamp,
	varchar,
} from "drizzle-orm/mysql-core";

export const comparisons = mysqlTable("comparisons", {
	// UUID, generated by the application (not the database) — see docs/ARCHITECTURE.md "Identifiers"
	id: char("id", { length: 36 }).primaryKey(),

	publicId: varchar("public_id", { length: 24 }).notNull().unique(),

	// hash only; the plaintext management token is never stored
	managementTokenHash: varchar("management_token_hash", { length: 255 })
		.notNull()
		.unique(),

	title: varchar("title", { length: 255 }),
	description: text("description"),
	referenceLabel: varchar("reference_label", { length: 255 }),
	captureLabel: varchar("capture_label", { length: 255 }),

	referencePath: varchar("reference_path", { length: 500 }).notNull(),
	capturePath: varchar("capture_path", { length: 500 }).notNull(),

	createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
	updatedAt: timestamp("updated_at", { mode: "date" })
		.notNull()
		.defaultNow()
		.onUpdateNow(),
});

export type Comparison = typeof comparisons.$inferSelect;
export type NewComparison = typeof comparisons.$inferInsert;
