// The Context Inspector's Output Inspector (docs/APPLICATION_LAYOUT.md
// "Output Inspector"), replacing the Edit Inspector once the user selects
// "Create Output" (src/components/EditInspector.tsx). The Presentation
// Preview stays mounted and unchanged behind it — this component never
// touches Current Working State, only reads it once per generation
// (src/lib/generate-comparison-output.ts).
//
// Snapshot only at Generate (docs/IMPORTED_COMPARISON_V1.md "Outcome
// Snapshot"): nothing here is computed until the primary action is
// pressed. Download behavior is the approved "Variante A": generation
// completes fully first, then the browser download is triggered exactly
// once automatically with no success/failure detection (no reliable
// browser signal exists — see docs/IMPLEMENTATION_PLAN_V1.md Phase 9's own
// Risks entry). Completion (docs/APPLICATION_LAYOUT.md "Completion": "No
// dedicated success screen is displayed") shows no success card or message
// of any kind — the browser download itself is the only success feedback;
// the primary action simply becomes `Download again`, which re-triggers the
// same already-generated bytes, never a new generation cycle. A generation
// failure never triggers any download and always shows the error state
// instead.
//
// `Download again` validity (docs/APPLICATION_LAYOUT.md "Completion": "The
// primary action remains a repeat download of the same generated artifact
// only while the selected output type and output-specific settings still
// match those it was generated with"): changing the output type, `Use
// current slider position` or `Remove embedded location data` invalidates
// the already-generated artifact for repeat download — see
// `invalidateGeneratedArtifact` below, called from each of those three
// controls' own change handlers, never from a separate effect watching
// them. A Presentation Preview slider movement alone does not call it. The
// previously generated bytes themselves are never touched — only this
// component's own reference to them for a future `Download again` click.

import { useRef, useState } from "react";
import { flushSync } from "react-dom";
import { useLocale } from "../i18n/LocaleContext";
import type { ComparisonPresentation } from "../lib/comparison-presentation";
import {
	type GenerateComparisonOutputPhase,
	generateComparisonOutput,
	type OutputType,
} from "../lib/generate-comparison-output";
import { DEFAULT_INITIAL_SLIDER_POSITION } from "../lib/outcome-snapshot";
import {
	type GeneratedArtifact,
	triggerDownload,
} from "../lib/trigger-download";
import type { CurrentWorkingState } from "../lib/workspace-state";

interface OutputInspectorProps {
	readonly currentWorkingState: CurrentWorkingState;
	readonly presentation: ComparisonPresentation;
	readonly onBackToEdit: () => void;
	// Reads src/components/WorkspaceActive.tsx's own live mirror of the
	// Presentation Preview's current Comparison Stage divider position (a
	// 0-100 value, ComparisonSlider's own scale) — called at most once, at
	// the moment Generate is pressed while "Use current slider position" is
	// on. Never read continuously, never stored here.
	readonly getCurrentSliderPosition: () => number;
}

type Phase = "idle" | "generating" | "ready" | "error";

// Phase 12 (docs/IMPLEMENTATION_PLAN_V1.md "Embed in Website Output
// Selection"): the Output Inspector's own selectable output-type set is
// wider than what generation currently supports (`OutputType`, from
// generate-comparison-output.ts) — Embed in website is selectable and
// configurable here but has no working Generate action yet
// (docs/EMBED_IN_WEBSITE.md "Output Inspector Behavior": "this phase adds
// selection UI only"). Kept as a separate type so generateComparisonOutput's
// own OutputType union never has to widen for a state runGeneration already
// guards against below.
type SelectableOutputType = OutputType | "embed-in-website";

// docs/WORDPRESS_INTEGRATION.md / docs/JOOMLA_INTEGRATION.md: WordPress and
// Joomla are the two Embed platforms selectable so far
// (docs/EMBED_IN_WEBSITE.md "Supported Platforms" — Webflow/Squarespace are
// approved product scope but not planned by this phase). Joomla has no
// working "Generate" action yet (docs/IMPLEMENTATION_PLAN_V1.md Phase 20
// "Not included": actual Joomla package generation is Phase 21) — selecting
// it only changes this Output Inspector's own state, per runGeneration's own
// guard below.
type EmbedPlatform = "wordpress" | "joomla";

// Yields across exactly two real browser animation frames rather than a
// fixed delay or a microtask-only `await Promise.resolve()` (which never
// guarantees an actual paint): the outer callback fires once the
// "starting-download" state React committed via flushSync (below) is about
// to be painted; the inner callback, scheduled from within it, only runs on
// the *following* frame — after that paint has already been presented. This
// is the smallest render-cycle boundary that is technically meaningful here;
// it is not tuned for, or lengthened to accommodate, any test's ability to
// observe it. Used once, below, so the "Starting download" progress phase
// (docs/APPLICATION_LAYOUT.md "Progress") has actually been committed and
// painted at least once before the Completion state replaces it.
function waitForNextPaint(): Promise<void> {
	return new Promise((resolve) => {
		requestAnimationFrame(() => {
			requestAnimationFrame(() => resolve());
		});
	});
}

// docs/BRAND_GUIDE.md Brand Identity Color — the same dark background used
// throughout this application; the generated artifact's own `theme-color`.
const THEME_COLOR = "#0D1424";

export default function OutputInspector({
	currentWorkingState,
	presentation,
	onBackToEdit,
	getCurrentSliderPosition,
}: OutputInspectorProps) {
	const { locale, t } = useLocale();
	const [outputType, setOutputType] =
		useState<SelectableOutputType>("standalone-html");
	// Embed's own platform selection (docs/EMBED_IN_WEBSITE.md "Output
	// Inspector Behavior"): explicit state rather than derived from "the only
	// option", per the same document's "Changing the selected platform
	// changes only the target/packaging of the next generated outcome" — a
	// real, if currently single-valued, piece of output-specific state.
	const [embedPlatform, setEmbedPlatform] =
		useState<EmbedPlatform>("wordpress");
	// Output-specific only (docs/COMPARISON_PRESENTATION.md "Use Current
	// Slider Position"): never part of Current Working State, never affects
	// the Workspace Preview, resets to its default whenever this component
	// remounts (WorkspaceActive renders EditInspector/OutputInspector as
	// mutually exclusive alternatives — see EditInspector.tsx's own header
	// comment for the confirmed remount behavior this relies on).
	const [useCurrentSliderPosition, setUseCurrentSliderPosition] =
		useState(false);
	const [removeEmbeddedLocationData, setRemoveEmbeddedLocationData] =
		useState(true);
	const [phase, setPhase] = useState<Phase>("idle");
	const [progressPhase, setProgressPhase] = useState<
		GenerateComparisonOutputPhase | "starting-download" | null
	>(null);
	const artifactRef = useRef<GeneratedArtifact | null>(null);

	const showLocationVisible =
		currentWorkingState.presentationVisibility.location;

	async function runGeneration() {
		// docs/IMPLEMENTATION_PLAN_V1.md Phase 15: Embed in website has a
		// working Generate action for WordPress. Phase 20 adds Joomla as a
		// second selectable platform, but its own package generation is Phase
		// 21 — `OutputType` (generate-comparison-output.ts) still has no
		// `"embed-joomla"` member. The primary action is disabled whenever
		// Joomla is selected (see the button below), so this function never
		// actually runs for it; this guard exists so a future regression in
		// that disabled state can never silently generate the wrong artifact.
		if (outputType === "embed-in-website" && embedPlatform === "joomla") {
			return;
		}
		const resolvedOutputType: OutputType =
			outputType === "embed-in-website" ? "embed-wordpress" : outputType;
		setPhase("generating");
		setProgressPhase("preparing-comparison");
		// Snapshotted here, once, at the moment Generate is pressed — never
		// re-read afterwards, so later Workspace Preview slider movement never
		// changes an already-generated output (docs/COMPARISON_PRESENTATION.md
		// "Use Current Slider Position").
		const initialSliderPosition = useCurrentSliderPosition
			? getCurrentSliderPosition() / 100
			: DEFAULT_INITIAL_SLIDER_POSITION;
		const result = await generateComparisonOutput({
			currentWorkingState,
			locale,
			presentationOptions: {
				referenceFallbackLabel: t.workspace.referenceFallbackLabel,
				sliderLabelFallbacks: {
					past: t.workspace.sliderPastLabel,
					present: t.workspace.sliderPresentLabel,
					reference: t.workspace.sliderReferenceLabel,
					current: t.workspace.sliderCurrentLabel,
				},
				durationLabelFallbacks: {
					year: t.workspace.durationYearLabel,
					years: t.workspace.durationYearsLabel,
					month: t.workspace.durationMonthLabel,
					months: t.workspace.durationMonthsLabel,
					sameYear: t.workspace.durationSameYearLabel,
				},
			},
			outputType: resolvedOutputType,
			removeEmbeddedLocationData,
			copy: {
				referenceAlt: t.workspace.referenceImageAlt,
				captureAlt: t.workspace.captureImageAlt,
				sliderLabel: t.workspace.sliderLabel,
				loadingLabel: t.workspace.loadingLabel,
			},
			titleText: presentation.title || t.outputInspector.artifactTitleFallback,
			metaDescriptionText: t.outputInspector.artifactMetaDescription,
			themeColor: THEME_COLOR,
			noscriptText: t.outputInspector.artifactNoscriptHint,
			initialSliderPosition,
			onPhase: (nextPhase) => setProgressPhase(nextPhase),
		});

		if (!result.ok) {
			artifactRef.current = null;
			setPhase("error");
			setProgressPhase(null);
			return;
		}

		// flushSync forces this specific update to commit to the DOM
		// immediately and on its own, rather than risk React's automatic
		// batching folding it into the "ready" update three lines below (both
		// occur in the same async continuation, with no React-visible event
		// boundary between them) — empirically confirmed necessary: without
		// it, "starting-download" was never actually painted even once,
		// batched-away regardless of the waitForNextPaint() delay that
		// follows.
		flushSync(() => setProgressPhase("starting-download"));
		await waitForNextPaint();
		artifactRef.current = result.value;
		triggerDownload(result.value);
		setPhase("ready");
		setProgressPhase(null);
	}

	function handleDownloadAgain() {
		if (artifactRef.current) triggerDownload(artifactRef.current);
	}

	// Invalidates the already-generated artifact for repeat download
	// (docs/APPLICATION_LAYOUT.md "Completion") — called from the output type
	// and the two output-specific settings' own change handlers below, each
	// time their value actually changes. Never called for a Presentation
	// Preview slider movement, which is not one of these three.
	function invalidateGeneratedArtifact() {
		setPhase("idle");
		artifactRef.current = null;
	}

	function selectOutputType(next: SelectableOutputType) {
		if (next === outputType) return;
		setOutputType(next);
		invalidateGeneratedArtifact();
	}

	// Same invalidation rule as selectOutputType and the two settings toggles
	// below (docs/APPLICATION_LAYOUT.md "Completion").
	function selectEmbedPlatform(next: EmbedPlatform) {
		if (next === embedPlatform) return;
		setEmbedPlatform(next);
		invalidateGeneratedArtifact();
	}

	function toggleUseCurrentSliderPosition() {
		setUseCurrentSliderPosition((current) => !current);
		invalidateGeneratedArtifact();
	}

	function toggleRemoveEmbeddedLocationData() {
		setRemoveEmbeddedLocationData((current) => !current);
		invalidateGeneratedArtifact();
	}

	const isGenerating = phase === "generating";
	// docs/IMPLEMENTATION_PLAN_V1.md Phase 20: while Embed in website is
	// selected, the label depends on the chosen platform — Joomla has no
	// working Generate action yet (Phase 21), so its own disabled-state label
	// must never claim a WordPress-specific action.
	const primaryLabel =
		outputType === "standalone-html"
			? t.outputInspector.downloadHtmlButton
			: outputType === "embed-in-website"
				? embedPlatform === "joomla"
					? t.outputInspector.joomlaNotAvailableButton
					: t.outputInspector.downloadWordPressButton
				: t.outputInspector.downloadZipButton;
	const embedGenerateUnavailable =
		outputType === "embed-in-website" && embedPlatform === "joomla";

	const progressLabel =
		progressPhase === "preparing-comparison"
			? t.outputInspector.progressPreparingComparison
			: progressPhase === "processing-images"
				? t.outputInspector.progressProcessingImages
				: progressPhase === "building-output"
					? t.outputInspector.progressBuildingOutput
					: progressPhase === "starting-download"
						? t.outputInspector.progressStartingDownload
						: "";

	return (
		<aside
			className="output-inspector"
			aria-label={t.outputInspector.heading}
			data-testid="output-inspector"
		>
			<button
				type="button"
				className="output-inspector__back-button"
				data-testid="output-inspector-back-button"
				onClick={onBackToEdit}
				disabled={isGenerating}
			>
				{t.outputInspector.backToEditButton}
			</button>

			<h2 className="output-inspector__heading">{t.outputInspector.heading}</h2>

			<div
				className="output-inspector__cards"
				role="radiogroup"
				aria-label={t.outputInspector.heading}
			>
				{/* A native <input type="radio"> cannot host the name+description
				    content each card needs — mirrors src/components/PresentationSection.tsx's
				    own OptionGroup, which documents the identical reason. */}
				{/* biome-ignore lint/a11y/useSemanticElements: see comment above */}
				<button
					type="button"
					role="radio"
					aria-checked={outputType === "standalone-html"}
					className={`output-inspector__card${
						outputType === "standalone-html"
							? " output-inspector__card--selected"
							: ""
					}`}
					data-testid="output-card-standalone-html"
					onClick={() => selectOutputType("standalone-html")}
					disabled={isGenerating}
				>
					<span className="output-inspector__card-name">
						{t.outputInspector.standaloneName}
					</span>
					<span className="output-inspector__card-description">
						{t.outputInspector.standaloneDescription}
					</span>
				</button>
				{/* biome-ignore lint/a11y/useSemanticElements: see comment above */}
				<button
					type="button"
					role="radio"
					aria-checked={outputType === "static-microsite"}
					className={`output-inspector__card${
						outputType === "static-microsite"
							? " output-inspector__card--selected"
							: ""
					}`}
					data-testid="output-card-static-microsite"
					onClick={() => selectOutputType("static-microsite")}
					disabled={isGenerating}
				>
					<span className="output-inspector__card-name">
						{t.outputInspector.micrositeName}
					</span>
					<span className="output-inspector__card-description">
						{t.outputInspector.micrositeDescription}
					</span>
				</button>
				{/* The platform selector below is a second, separate interactive
				    control and must not nest inside the radio button that selects
				    this output type (docs/EMBED_IN_WEBSITE.md "Output Inspector
				    Behavior"); this wrapper div carries the card's visual styling
				    instead, exactly as the plain <button> does for the two cards
				    above. */}
				<div
					className={`output-inspector__card${
						outputType === "embed-in-website"
							? " output-inspector__card--selected"
							: ""
					}`}
				>
					{/* biome-ignore lint/a11y/useSemanticElements: see the comment on the two cards above */}
					<button
						type="button"
						role="radio"
						aria-checked={outputType === "embed-in-website"}
						className="output-inspector__card-select"
						data-testid="output-card-embed-in-website"
						onClick={() => selectOutputType("embed-in-website")}
						disabled={isGenerating}
					>
						<span className="output-inspector__card-name">
							{t.outputInspector.embedName}
						</span>
						<span className="output-inspector__card-description">
							{t.outputInspector.embedDescription}
						</span>
					</button>
					<div
						className="output-inspector__platform-selector"
						role="radiogroup"
						aria-label={t.outputInspector.embedPlatformLabel}
					>
						<span className="output-inspector__platform-label">
							{t.outputInspector.embedPlatformLabel}
						</span>
						{/* WordPress and Joomla are the two Embed platforms offered so far
						    (docs/EMBED_IN_WEBSITE.md "Supported Platforms"); no Webflow or
						    Squarespace option is offered yet. */}
						{/* biome-ignore lint/a11y/useSemanticElements: see the comment on the two radiogroups above */}
						<button
							type="button"
							role="radio"
							aria-checked={embedPlatform === "wordpress"}
							className={`output-inspector__platform-option${
								embedPlatform === "wordpress"
									? " output-inspector__platform-option--selected"
									: ""
							}`}
							data-testid="output-platform-wordpress"
							onClick={() => selectEmbedPlatform("wordpress")}
							disabled={outputType !== "embed-in-website" || isGenerating}
						>
							WordPress
						</button>
						{/* biome-ignore lint/a11y/useSemanticElements: see the comment on the two radiogroups above */}
						<button
							type="button"
							role="radio"
							aria-checked={embedPlatform === "joomla"}
							className={`output-inspector__platform-option${
								embedPlatform === "joomla"
									? " output-inspector__platform-option--selected"
									: ""
							}`}
							data-testid="output-platform-joomla"
							onClick={() => selectEmbedPlatform("joomla")}
							disabled={outputType !== "embed-in-website" || isGenerating}
						>
							Joomla
						</button>
					</div>
				</div>
			</div>

			<div className="output-inspector__field-row">
				<span
					id="output-use-current-slider-position-label"
					className="output-inspector__toggle-label"
				>
					{t.outputInspector.useCurrentSliderPositionLabel}
				</span>
				<button
					type="button"
					role="switch"
					aria-checked={useCurrentSliderPosition}
					aria-labelledby="output-use-current-slider-position-label"
					data-testid="output-use-current-slider-position-switch"
					className={`switch${useCurrentSliderPosition ? " switch--on" : ""}`}
					onClick={toggleUseCurrentSliderPosition}
					disabled={isGenerating}
				>
					<span className="switch__track">
						<span className="switch__thumb" />
					</span>
				</button>
			</div>
			<p className="output-inspector__hint">
				{t.outputInspector.useCurrentSliderPositionHint}
			</p>

			<div className="output-inspector__field-row">
				<span
					id="output-remove-location-data-label"
					className="output-inspector__toggle-label"
				>
					{t.outputInspector.removeLocationDataLabel}
				</span>
				<button
					type="button"
					role="switch"
					aria-checked={removeEmbeddedLocationData}
					aria-labelledby="output-remove-location-data-label"
					data-testid="output-remove-location-data-switch"
					className={`switch${removeEmbeddedLocationData ? " switch--on" : ""}`}
					onClick={toggleRemoveEmbeddedLocationData}
					disabled={isGenerating}
				>
					<span className="switch__track">
						<span className="switch__thumb" />
					</span>
				</button>
			</div>
			{removeEmbeddedLocationData && showLocationVisible && (
				<p
					className="output-inspector__hint"
					data-testid="output-remove-location-data-hint"
				>
					{t.outputInspector.removeLocationDataHint}
				</p>
			)}

			{phase === "generating" && (
				<div
					className="output-inspector__progress"
					data-testid="output-progress"
					data-phase={progressPhase}
					aria-live="polite"
				>
					<span className="output-inspector__progress-bar" aria-hidden="true" />
					<span data-testid="output-progress-label">{progressLabel}</span>
				</div>
			)}

			{phase === "error" && (
				<div
					className="output-inspector__error"
					data-testid="output-error"
					role="alert"
				>
					<p className="output-inspector__error-heading">
						{t.outputInspector.errorHeading}
					</p>
					<p>{t.outputInspector.errorMessage}</p>
				</div>
			)}

			<button
				type="button"
				className="output-inspector__primary-button"
				data-testid="output-primary-action"
				onClick={phase === "ready" ? handleDownloadAgain : runGeneration}
				disabled={isGenerating || embedGenerateUnavailable}
			>
				{phase === "ready"
					? t.outputInspector.downloadAgainButton
					: primaryLabel}
			</button>

			{/* docs/EMBED_IN_WEBSITE.md "Output Inspector Behavior": "After
			    successful generation, SameView Web shows a short platform-specific
			    installation/integration guide directly in the Output Inspector.
			    There is no wizard, modal or separate workflow page." Deferred from
			    Phase 12 (docs/IMPLEMENTATION_PLAN_V1.md Phase 12 "Not included":
			    "post-generation installation guidance content (Phase 15)"). */}
			{phase === "ready" && outputType === "embed-in-website" && (
				<p
					className="output-inspector__hint"
					data-testid="output-wordpress-install-guide"
				>
					{t.outputInspector.wordPressInstallGuide}
				</p>
			)}
		</aside>
	);
}
