CREATE TABLE `comparisons` (
	`id` char(36) NOT NULL,
	`comparison_id` char(36) NOT NULL,
	`public_id` varchar(12) NOT NULL,
	`management_token_hash` varchar(64) NOT NULL,
	`title` varchar(255),
	`description` text,
	`reference_label` varchar(255) NOT NULL,
	`capture_label` varchar(255) NOT NULL,
	`location_display_name` varchar(255),
	`location_city` varchar(255),
	`location_country` varchar(255),
	`branding_type` varchar(50),
	`branding_builtin_id` varchar(100),
	`background` varchar(10) NOT NULL,
	`corner_style` varchar(10) NOT NULL,
	`active_asset_version` varchar(36),
	`status` varchar(20) NOT NULL DEFAULT 'active',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `comparisons_id` PRIMARY KEY(`id`),
	CONSTRAINT `comparisons_comparison_id_unique` UNIQUE(`comparison_id`),
	CONSTRAINT `comparisons_public_id_unique` UNIQUE(`public_id`),
	CONSTRAINT `comparisons_management_token_hash_unique` UNIQUE(`management_token_hash`)
);
